[package]
name = "matting-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.78.0"
image = { version = "0.24.5", features = ["webp", "webp-encoder"] }